from aws_cdk import (
    Duration,
    Stack,
    aws_rds as rds,
    aws_ec2 as ec2,
    aws_ssm as ssm
)
from constructs import Construct

from LPugensWebCDK.StageConfigs import StageConfig


class DBStack(Stack):

    def __init__(
            self,
            scope: Construct,
            construct_id: str,
            vpc: ec2.Vpc,
            stage_config: StageConfig,
            backup_retention_days: int = 1,
            **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        self.vpc = vpc
        self.backup_retention_days = backup_retention_days

        # Our network in the cloud
        self.aurora_serverless_db = rds.ServerlessCluster(
            self,
            "AuroraServerlessCluster",
            engine=rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
            vpc=self.vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED),
            default_database_name='DjangoDB',
            backup_retention=Duration.days(self.backup_retention_days),  # 1 day retention is free
            deletion_protection=True,
            enable_data_api=True,  # Allow running queries in AWS console (free)
            parameter_group=rds.ParameterGroup.from_parameter_group_name(  # Specify the postgresql version
                self,
                "AuroraDBParameterGroup",
                "default.aurora-postgresql10"  # Only this version is supported for Aurora Serverless now
            ),
            scaling=stage_config.aurora_scaling,
        )
        # Allow ingress traffic from ECS tasks
        self.aurora_serverless_db.connections.allow_default_port_from_any_ipv4(
            description="Services in private subnets can access the DB"
        )
        # Save the name of the autogenerated secrets manager secret holding database credentials
        self.ssm_db_secret_name_param = ssm.StringParameter(
            self,
            "DatabaseSecretNameParam",
            parameter_name=f"/{scope.stage_name}/DatabaseSecretNameParam",
            string_value=self.aurora_serverless_db.secret.secret_name
        )
